//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerkTokgozBlogSitesi.Api.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Yorum = new HashSet<Yorum>();
            this.Etiket = new HashSet<Etiket>();
            this.Resimler1 = new HashSet<Resimler>();
        }
    
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string İcerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> KapakResimID { get; set; }
        public Nullable<int> Goruntulenme { get; set; }
        public Nullable<int> Begeni { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> YazarID { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Resimler Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiket> Etiket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resimler> Resimler1 { get; set; }
    }
}
