//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerkTokgozBlogSitesi.Api.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public string Mesaj { get; set; }
        public string Tarih { get; set; }
        public bool Goruldu { get; set; }
        public int Gonderen { get; set; }
        public int Alan { get; set; }
    }
}
