//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerkTokgozBlogSitesi.Api.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string İcerik { get; set; }
        public int MakaleID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int YazarID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Makale Makale { get; set; }
    }
}
